version: '3.8'

services:
  byteblaze:
    build: .
    image: byteblaze:latest
    container_name: byteblaze
    restart: unless-stopped
    environment:
      - NODE_HOST=lavalink
      - NODE_PORT=2333
      - NODE_AUTH=Min2302
      # Database
      - MONGO_URI=mongodb://root:yap0Cv0sRRp2nwec@mongo:27017/byteblaze?authSource=admin
    networks:
      - lavanet
networks:
  lavanet:
    external: true
    name: lavalink_lavanet